version: '3'

services:
  backitup:
    image: alinmear/docker-backitup:latest
    volumes:
      - /tmp/backup_src:/backup_root
      - /tmp/backup:/backup
    links:
      - mariadb:mysql
    environment:
        MYSQL_USER: root
        MYSQL_PASS: root
    cap_add:
        - SYS_PTRACE

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
